# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title
plugins: [jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :compressed

baseurl: https://poabitdevs.com

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title: "BitDevs em Português"
description: "BitDevs é uma comunidade para aqueles interessados em discutir e participar na pesquisa e desenvolvimento do Bitcoin e protocolos relacionados."

# Leave out some files
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.sass-cache']

# Render events with a future date
future: true

